// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package user

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SendEmailCodeReq struct {
	Email                string   `protobuf:"bytes,1,opt,name=Email,proto3" json:"Email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendEmailCodeReq) Reset()         { *m = SendEmailCodeReq{} }
func (m *SendEmailCodeReq) String() string { return proto.CompactTextString(m) }
func (*SendEmailCodeReq) ProtoMessage()    {}
func (*SendEmailCodeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *SendEmailCodeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendEmailCodeReq.Unmarshal(m, b)
}
func (m *SendEmailCodeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendEmailCodeReq.Marshal(b, m, deterministic)
}
func (m *SendEmailCodeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendEmailCodeReq.Merge(m, src)
}
func (m *SendEmailCodeReq) XXX_Size() int {
	return xxx_messageInfo_SendEmailCodeReq.Size(m)
}
func (m *SendEmailCodeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SendEmailCodeReq.DiscardUnknown(m)
}

var xxx_messageInfo_SendEmailCodeReq proto.InternalMessageInfo

func (m *SendEmailCodeReq) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type SendEmailCodeResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendEmailCodeResp) Reset()         { *m = SendEmailCodeResp{} }
func (m *SendEmailCodeResp) String() string { return proto.CompactTextString(m) }
func (*SendEmailCodeResp) ProtoMessage()    {}
func (*SendEmailCodeResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *SendEmailCodeResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendEmailCodeResp.Unmarshal(m, b)
}
func (m *SendEmailCodeResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendEmailCodeResp.Marshal(b, m, deterministic)
}
func (m *SendEmailCodeResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendEmailCodeResp.Merge(m, src)
}
func (m *SendEmailCodeResp) XXX_Size() int {
	return xxx_messageInfo_SendEmailCodeResp.Size(m)
}
func (m *SendEmailCodeResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SendEmailCodeResp.DiscardUnknown(m)
}

var xxx_messageInfo_SendEmailCodeResp proto.InternalMessageInfo

type AuthByEmailCodeReq struct {
	Email                string   `protobuf:"bytes,1,opt,name=Email,proto3" json:"Email,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=Code,proto3" json:"Code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthByEmailCodeReq) Reset()         { *m = AuthByEmailCodeReq{} }
func (m *AuthByEmailCodeReq) String() string { return proto.CompactTextString(m) }
func (*AuthByEmailCodeReq) ProtoMessage()    {}
func (*AuthByEmailCodeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *AuthByEmailCodeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthByEmailCodeReq.Unmarshal(m, b)
}
func (m *AuthByEmailCodeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthByEmailCodeReq.Marshal(b, m, deterministic)
}
func (m *AuthByEmailCodeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthByEmailCodeReq.Merge(m, src)
}
func (m *AuthByEmailCodeReq) XXX_Size() int {
	return xxx_messageInfo_AuthByEmailCodeReq.Size(m)
}
func (m *AuthByEmailCodeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthByEmailCodeReq.DiscardUnknown(m)
}

var xxx_messageInfo_AuthByEmailCodeReq proto.InternalMessageInfo

func (m *AuthByEmailCodeReq) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *AuthByEmailCodeReq) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type AuthByEmailCodeResp struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthByEmailCodeResp) Reset()         { *m = AuthByEmailCodeResp{} }
func (m *AuthByEmailCodeResp) String() string { return proto.CompactTextString(m) }
func (*AuthByEmailCodeResp) ProtoMessage()    {}
func (*AuthByEmailCodeResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *AuthByEmailCodeResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthByEmailCodeResp.Unmarshal(m, b)
}
func (m *AuthByEmailCodeResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthByEmailCodeResp.Marshal(b, m, deterministic)
}
func (m *AuthByEmailCodeResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthByEmailCodeResp.Merge(m, src)
}
func (m *AuthByEmailCodeResp) XXX_Size() int {
	return xxx_messageInfo_AuthByEmailCodeResp.Size(m)
}
func (m *AuthByEmailCodeResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthByEmailCodeResp.DiscardUnknown(m)
}

var xxx_messageInfo_AuthByEmailCodeResp proto.InternalMessageInfo

func (m *AuthByEmailCodeResp) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

type AuthByIDPasswordReq struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthByIDPasswordReq) Reset()         { *m = AuthByIDPasswordReq{} }
func (m *AuthByIDPasswordReq) String() string { return proto.CompactTextString(m) }
func (*AuthByIDPasswordReq) ProtoMessage()    {}
func (*AuthByIDPasswordReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *AuthByIDPasswordReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthByIDPasswordReq.Unmarshal(m, b)
}
func (m *AuthByIDPasswordReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthByIDPasswordReq.Marshal(b, m, deterministic)
}
func (m *AuthByIDPasswordReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthByIDPasswordReq.Merge(m, src)
}
func (m *AuthByIDPasswordReq) XXX_Size() int {
	return xxx_messageInfo_AuthByIDPasswordReq.Size(m)
}
func (m *AuthByIDPasswordReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthByIDPasswordReq.DiscardUnknown(m)
}

var xxx_messageInfo_AuthByIDPasswordReq proto.InternalMessageInfo

func (m *AuthByIDPasswordReq) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *AuthByIDPasswordReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type AuthByIDPasswordResp struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthByIDPasswordResp) Reset()         { *m = AuthByIDPasswordResp{} }
func (m *AuthByIDPasswordResp) String() string { return proto.CompactTextString(m) }
func (*AuthByIDPasswordResp) ProtoMessage()    {}
func (*AuthByIDPasswordResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{5}
}

func (m *AuthByIDPasswordResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthByIDPasswordResp.Unmarshal(m, b)
}
func (m *AuthByIDPasswordResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthByIDPasswordResp.Marshal(b, m, deterministic)
}
func (m *AuthByIDPasswordResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthByIDPasswordResp.Merge(m, src)
}
func (m *AuthByIDPasswordResp) XXX_Size() int {
	return xxx_messageInfo_AuthByIDPasswordResp.Size(m)
}
func (m *AuthByIDPasswordResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthByIDPasswordResp.DiscardUnknown(m)
}

var xxx_messageInfo_AuthByIDPasswordResp proto.InternalMessageInfo

func (m *AuthByIDPasswordResp) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

type User struct {
	ID                   int64      `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Email                string     `protobuf:"bytes,2,opt,name=Email,proto3" json:"Email,omitempty"`
	Phone                string     `protobuf:"bytes,3,opt,name=Phone,proto3" json:"Phone,omitempty"`
	Name                 string     `protobuf:"bytes,4,opt,name=Name,proto3" json:"Name,omitempty"`
	Status               int32      `protobuf:"varint,5,opt,name=Status,proto3" json:"Status,omitempty"`
	Gender               int32      `protobuf:"varint,6,opt,name=Gender,proto3" json:"Gender,omitempty"`
	BirthDate            int64      `protobuf:"varint,7,opt,name=BirthDate,proto3" json:"BirthDate,omitempty"`
	CreatedAt            int64      `protobuf:"varint,8,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt            int64      `protobuf:"varint,9,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	Extra                *UserExtra `protobuf:"bytes,10,opt,name=Extra,proto3" json:"Extra,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{6}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *User) GetGender() int32 {
	if m != nil {
		return m.Gender
	}
	return 0
}

func (m *User) GetBirthDate() int64 {
	if m != nil {
		return m.BirthDate
	}
	return 0
}

func (m *User) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *User) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *User) GetExtra() *UserExtra {
	if m != nil {
		return m.Extra
	}
	return nil
}

type UserExtra struct {
	AvatarUrl            string   `protobuf:"bytes,1,opt,name=AvatarUrl,proto3" json:"AvatarUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserExtra) Reset()         { *m = UserExtra{} }
func (m *UserExtra) String() string { return proto.CompactTextString(m) }
func (*UserExtra) ProtoMessage()    {}
func (*UserExtra) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{7}
}

func (m *UserExtra) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserExtra.Unmarshal(m, b)
}
func (m *UserExtra) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserExtra.Marshal(b, m, deterministic)
}
func (m *UserExtra) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserExtra.Merge(m, src)
}
func (m *UserExtra) XXX_Size() int {
	return xxx_messageInfo_UserExtra.Size(m)
}
func (m *UserExtra) XXX_DiscardUnknown() {
	xxx_messageInfo_UserExtra.DiscardUnknown(m)
}

var xxx_messageInfo_UserExtra proto.InternalMessageInfo

func (m *UserExtra) GetAvatarUrl() string {
	if m != nil {
		return m.AvatarUrl
	}
	return ""
}

type MGetUserInfoReq struct {
	IDs                  []int64  `protobuf:"varint,1,rep,packed,name=IDs,proto3" json:"IDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MGetUserInfoReq) Reset()         { *m = MGetUserInfoReq{} }
func (m *MGetUserInfoReq) String() string { return proto.CompactTextString(m) }
func (*MGetUserInfoReq) ProtoMessage()    {}
func (*MGetUserInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{8}
}

func (m *MGetUserInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MGetUserInfoReq.Unmarshal(m, b)
}
func (m *MGetUserInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MGetUserInfoReq.Marshal(b, m, deterministic)
}
func (m *MGetUserInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MGetUserInfoReq.Merge(m, src)
}
func (m *MGetUserInfoReq) XXX_Size() int {
	return xxx_messageInfo_MGetUserInfoReq.Size(m)
}
func (m *MGetUserInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MGetUserInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_MGetUserInfoReq proto.InternalMessageInfo

func (m *MGetUserInfoReq) GetIDs() []int64 {
	if m != nil {
		return m.IDs
	}
	return nil
}

type MGetUserInfoResp struct {
	IDs                  []int64         `protobuf:"varint,1,rep,packed,name=IDs,proto3" json:"IDs,omitempty"`
	Users                map[int64]*User `protobuf:"bytes,2,rep,name=Users,proto3" json:"Users,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *MGetUserInfoResp) Reset()         { *m = MGetUserInfoResp{} }
func (m *MGetUserInfoResp) String() string { return proto.CompactTextString(m) }
func (*MGetUserInfoResp) ProtoMessage()    {}
func (*MGetUserInfoResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{9}
}

func (m *MGetUserInfoResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MGetUserInfoResp.Unmarshal(m, b)
}
func (m *MGetUserInfoResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MGetUserInfoResp.Marshal(b, m, deterministic)
}
func (m *MGetUserInfoResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MGetUserInfoResp.Merge(m, src)
}
func (m *MGetUserInfoResp) XXX_Size() int {
	return xxx_messageInfo_MGetUserInfoResp.Size(m)
}
func (m *MGetUserInfoResp) XXX_DiscardUnknown() {
	xxx_messageInfo_MGetUserInfoResp.DiscardUnknown(m)
}

var xxx_messageInfo_MGetUserInfoResp proto.InternalMessageInfo

func (m *MGetUserInfoResp) GetIDs() []int64 {
	if m != nil {
		return m.IDs
	}
	return nil
}

func (m *MGetUserInfoResp) GetUsers() map[int64]*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type UpdateUserInfoReq struct {
	ID                   int64      `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Phone                string     `protobuf:"bytes,2,opt,name=Phone,proto3" json:"Phone,omitempty"`
	Name                 string     `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Gender               int32      `protobuf:"varint,4,opt,name=Gender,proto3" json:"Gender,omitempty"`
	BirthDate            int64      `protobuf:"varint,5,opt,name=BirthDate,proto3" json:"BirthDate,omitempty"`
	UserExtra            *UserExtra `protobuf:"bytes,6,opt,name=UserExtra,proto3" json:"UserExtra,omitempty"`
	PassWord             string     `protobuf:"bytes,7,opt,name=PassWord,proto3" json:"PassWord,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *UpdateUserInfoReq) Reset()         { *m = UpdateUserInfoReq{} }
func (m *UpdateUserInfoReq) String() string { return proto.CompactTextString(m) }
func (*UpdateUserInfoReq) ProtoMessage()    {}
func (*UpdateUserInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{10}
}

func (m *UpdateUserInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserInfoReq.Unmarshal(m, b)
}
func (m *UpdateUserInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserInfoReq.Marshal(b, m, deterministic)
}
func (m *UpdateUserInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserInfoReq.Merge(m, src)
}
func (m *UpdateUserInfoReq) XXX_Size() int {
	return xxx_messageInfo_UpdateUserInfoReq.Size(m)
}
func (m *UpdateUserInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserInfoReq proto.InternalMessageInfo

func (m *UpdateUserInfoReq) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *UpdateUserInfoReq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *UpdateUserInfoReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateUserInfoReq) GetGender() int32 {
	if m != nil {
		return m.Gender
	}
	return 0
}

func (m *UpdateUserInfoReq) GetBirthDate() int64 {
	if m != nil {
		return m.BirthDate
	}
	return 0
}

func (m *UpdateUserInfoReq) GetUserExtra() *UserExtra {
	if m != nil {
		return m.UserExtra
	}
	return nil
}

func (m *UpdateUserInfoReq) GetPassWord() string {
	if m != nil {
		return m.PassWord
	}
	return ""
}

type UpdateUserInfoResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserInfoResp) Reset()         { *m = UpdateUserInfoResp{} }
func (m *UpdateUserInfoResp) String() string { return proto.CompactTextString(m) }
func (*UpdateUserInfoResp) ProtoMessage()    {}
func (*UpdateUserInfoResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{11}
}

func (m *UpdateUserInfoResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserInfoResp.Unmarshal(m, b)
}
func (m *UpdateUserInfoResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserInfoResp.Marshal(b, m, deterministic)
}
func (m *UpdateUserInfoResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserInfoResp.Merge(m, src)
}
func (m *UpdateUserInfoResp) XXX_Size() int {
	return xxx_messageInfo_UpdateUserInfoResp.Size(m)
}
func (m *UpdateUserInfoResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserInfoResp.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserInfoResp proto.InternalMessageInfo

func init() {
	proto.RegisterType((*SendEmailCodeReq)(nil), "user.SendEmailCodeReq")
	proto.RegisterType((*SendEmailCodeResp)(nil), "user.SendEmailCodeResp")
	proto.RegisterType((*AuthByEmailCodeReq)(nil), "user.AuthByEmailCodeReq")
	proto.RegisterType((*AuthByEmailCodeResp)(nil), "user.AuthByEmailCodeResp")
	proto.RegisterType((*AuthByIDPasswordReq)(nil), "user.AuthByIDPasswordReq")
	proto.RegisterType((*AuthByIDPasswordResp)(nil), "user.AuthByIDPasswordResp")
	proto.RegisterType((*User)(nil), "user.User")
	proto.RegisterType((*UserExtra)(nil), "user.UserExtra")
	proto.RegisterType((*MGetUserInfoReq)(nil), "user.MGetUserInfoReq")
	proto.RegisterType((*MGetUserInfoResp)(nil), "user.MGetUserInfoResp")
	proto.RegisterMapType((map[int64]*User)(nil), "user.MGetUserInfoResp.UsersEntry")
	proto.RegisterType((*UpdateUserInfoReq)(nil), "user.UpdateUserInfoReq")
	proto.RegisterType((*UpdateUserInfoResp)(nil), "user.UpdateUserInfoResp")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 585 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x96, 0xed, 0xb8, 0x6d, 0x26, 0xd0, 0xa6, 0xd3, 0x50, 0x16, 0x8b, 0x83, 0x31, 0x42, 0x32,
	0x07, 0x7a, 0x08, 0x87, 0x56, 0x48, 0x20, 0xd2, 0x38, 0x54, 0x3e, 0x80, 0x2a, 0x87, 0x88, 0xb3,
	0x89, 0x17, 0x25, 0x6a, 0x6b, 0xbb, 0xbb, 0x9b, 0x40, 0x9e, 0x80, 0x07, 0xe1, 0x7d, 0x78, 0x0c,
	0x9e, 0x03, 0xad, 0xd7, 0x49, 0xfc, 0x17, 0xc1, 0x6d, 0xe7, 0xfb, 0xbe, 0xfd, 0x99, 0xfd, 0x66,
	0x06, 0x60, 0xc1, 0x29, 0x3b, 0x4b, 0x59, 0x22, 0x12, 0x6c, 0xc9, 0xb5, 0xe3, 0x42, 0x77, 0x4c,
	0xe3, 0x68, 0x74, 0x17, 0xce, 0x6f, 0x87, 0x49, 0x44, 0x03, 0x7a, 0x8f, 0x3d, 0x30, 0xb3, 0x98,
	0x68, 0xb6, 0xe6, 0xb6, 0x03, 0x15, 0x38, 0x27, 0x70, 0x5c, 0x51, 0xf2, 0xd4, 0x79, 0x07, 0x38,
	0x58, 0x88, 0xd9, 0xe5, 0xea, 0xdf, 0x07, 0x20, 0x42, 0x4b, 0x0a, 0x88, 0x9e, 0x81, 0xd9, 0xda,
	0x39, 0x87, 0x93, 0xda, 0x7e, 0x9e, 0xa2, 0x0d, 0x9d, 0xc1, 0x74, 0x4a, 0x39, 0xff, 0x9c, 0xdc,
	0xd0, 0x38, 0x3f, 0xa6, 0x08, 0x39, 0x83, 0xf5, 0x46, 0xdf, 0xbb, 0x0e, 0x39, 0xff, 0x9e, 0xb0,
	0x48, 0xde, 0x7c, 0x08, 0xba, 0xef, 0x65, 0x7a, 0x23, 0xd0, 0x7d, 0x0f, 0x2d, 0x38, 0x58, 0xd3,
	0xf9, 0xbd, 0x9b, 0xd8, 0xb9, 0x80, 0x5e, 0xfd, 0x88, 0xff, 0xba, 0xfc, 0xa7, 0x0e, 0xad, 0x09,
	0xa7, 0xac, 0x76, 0xdd, 0x26, 0x71, 0xbd, 0x98, 0x78, 0x0f, 0xcc, 0xeb, 0x59, 0x12, 0x53, 0x62,
	0x28, 0x34, 0x0b, 0xe4, 0x77, 0x7c, 0x0a, 0xef, 0x28, 0x69, 0xa9, 0xef, 0x90, 0x6b, 0x3c, 0x85,
	0xbd, 0xb1, 0x08, 0xc5, 0x82, 0x13, 0xd3, 0xd6, 0x5c, 0x33, 0xc8, 0x23, 0x89, 0x5f, 0xd1, 0x38,
	0xa2, 0x8c, 0xec, 0x29, 0x5c, 0x45, 0xf8, 0x14, 0xda, 0x97, 0x73, 0x26, 0x66, 0x5e, 0x28, 0x28,
	0xd9, 0xcf, 0x9e, 0xb1, 0x05, 0x24, 0x3b, 0x64, 0x34, 0x14, 0x34, 0x1a, 0x08, 0x72, 0xa0, 0xd8,
	0x0d, 0x20, 0xd9, 0x49, 0x1a, 0xe5, 0x6c, 0x5b, 0xb1, 0x1b, 0x00, 0x5f, 0x80, 0x39, 0xfa, 0x21,
	0x58, 0x48, 0xc0, 0xd6, 0xdc, 0x4e, 0xff, 0xe8, 0x2c, 0xab, 0x1c, 0x99, 0x74, 0x06, 0x07, 0x8a,
	0x75, 0x5e, 0x42, 0x7b, 0x83, 0xc9, 0x13, 0x07, 0xcb, 0x50, 0x84, 0x6c, 0xc2, 0xd6, 0xd6, 0x6f,
	0x01, 0xe7, 0x39, 0x1c, 0x7d, 0xbc, 0xa2, 0x42, 0xca, 0xfd, 0xf8, 0x5b, 0x22, 0xdd, 0xea, 0x82,
	0xe1, 0x7b, 0x9c, 0x68, 0xb6, 0xe1, 0x1a, 0x81, 0x5c, 0x3a, 0xbf, 0x34, 0xe8, 0x96, 0x55, 0x3c,
	0xad, 0xcb, 0xf0, 0x1c, 0x4c, 0xa9, 0xe0, 0x44, 0xb7, 0x0d, 0xb7, 0xd3, 0x7f, 0xa6, 0x5e, 0x57,
	0xdd, 0x98, 0x3d, 0x97, 0x8f, 0x62, 0xc1, 0x56, 0x81, 0xd2, 0x5b, 0x1e, 0xc0, 0x16, 0x94, 0x07,
	0xdf, 0xd0, 0x55, 0xee, 0x9f, 0x5c, 0xa2, 0x0d, 0xe6, 0x32, 0xbc, 0x5d, 0xa8, 0x22, 0xed, 0xf4,
	0x61, 0x9b, 0x76, 0xa0, 0x88, 0x37, 0xfa, 0x85, 0xe6, 0xfc, 0xd6, 0xe0, 0x58, 0x7d, 0x55, 0x31,
	0x9b, 0x86, 0x62, 0x50, 0xb6, 0xeb, 0x4d, 0xb6, 0x1b, 0x65, 0xdb, 0x73, 0x7b, 0x5b, 0xbb, 0xed,
	0x35, 0xab, 0xf6, 0xbe, 0x2a, 0xfc, 0x7d, 0x56, 0x17, 0x0d, 0x36, 0x15, 0xdc, 0xc9, 0x5b, 0xe1,
	0x8b, 0x6c, 0x85, 0xfd, 0x6d, 0x2b, 0xc8, 0xd8, 0xe9, 0x01, 0x56, 0xf3, 0xe1, 0x69, 0xff, 0x8f,
	0x0e, 0x1d, 0x09, 0x8c, 0x29, 0x5b, 0xce, 0xa7, 0x14, 0xdf, 0xc3, 0xc3, 0xd2, 0x04, 0xc0, 0x53,
	0x75, 0x5d, 0x75, 0x80, 0x58, 0x8f, 0x1b, 0x71, 0x9e, 0xe2, 0x07, 0x38, 0xaa, 0xb4, 0x3b, 0x12,
	0xa5, 0xad, 0x4f, 0x11, 0xeb, 0xc9, 0x0e, 0x86, 0xa7, 0xe8, 0x43, 0xb7, 0xda, 0xba, 0x58, 0x92,
	0x97, 0xa6, 0x82, 0x65, 0xed, 0xa2, 0x78, 0x8a, 0x6f, 0xe1, 0x41, 0xb1, 0x6e, 0xf0, 0x51, 0x53,
	0x2d, 0xdd, 0x5b, 0xa7, 0xcd, 0x25, 0x86, 0x43, 0x38, 0x2c, 0xff, 0x1c, 0xe6, 0xc9, 0xd7, 0xea,
	0xc3, 0x22, 0xcd, 0x04, 0x4f, 0xbf, 0xee, 0x65, 0x13, 0xf9, 0xf5, 0xdf, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xf8, 0x36, 0x68, 0xcc, 0x9f, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	// 邮箱登陆认证发送验证吗
	SendEmailCode(ctx context.Context, in *SendEmailCodeReq, opts ...grpc.CallOption) (*SendEmailCodeResp, error)
	// 邮箱登陆认证 (没有注册过默认会注册一个账号)
	AuthByEmailCode(ctx context.Context, in *AuthByEmailCodeReq, opts ...grpc.CallOption) (*AuthByEmailCodeResp, error)
	// ID + 密码认证
	AuthByIDPassword(ctx context.Context, in *AuthByIDPasswordReq, opts ...grpc.CallOption) (*AuthByIDPasswordResp, error)
	// 批量获取指定用户ID 的基本信息
	MGetUserInfo(ctx context.Context, in *MGetUserInfoReq, opts ...grpc.CallOption) (*MGetUserInfoResp, error)
	// 修改指定用户ID 的基本信息
	UpdateUserInfo(ctx context.Context, in *UpdateUserInfoReq, opts ...grpc.CallOption) (*UpdateUserInfoResp, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) SendEmailCode(ctx context.Context, in *SendEmailCodeReq, opts ...grpc.CallOption) (*SendEmailCodeResp, error) {
	out := new(SendEmailCodeResp)
	err := c.cc.Invoke(ctx, "/user.UserService/SendEmailCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) AuthByEmailCode(ctx context.Context, in *AuthByEmailCodeReq, opts ...grpc.CallOption) (*AuthByEmailCodeResp, error) {
	out := new(AuthByEmailCodeResp)
	err := c.cc.Invoke(ctx, "/user.UserService/AuthByEmailCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) AuthByIDPassword(ctx context.Context, in *AuthByIDPasswordReq, opts ...grpc.CallOption) (*AuthByIDPasswordResp, error) {
	out := new(AuthByIDPasswordResp)
	err := c.cc.Invoke(ctx, "/user.UserService/AuthByIDPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) MGetUserInfo(ctx context.Context, in *MGetUserInfoReq, opts ...grpc.CallOption) (*MGetUserInfoResp, error) {
	out := new(MGetUserInfoResp)
	err := c.cc.Invoke(ctx, "/user.UserService/MGetUserInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateUserInfo(ctx context.Context, in *UpdateUserInfoReq, opts ...grpc.CallOption) (*UpdateUserInfoResp, error) {
	out := new(UpdateUserInfoResp)
	err := c.cc.Invoke(ctx, "/user.UserService/UpdateUserInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	// 邮箱登陆认证发送验证吗
	SendEmailCode(context.Context, *SendEmailCodeReq) (*SendEmailCodeResp, error)
	// 邮箱登陆认证 (没有注册过默认会注册一个账号)
	AuthByEmailCode(context.Context, *AuthByEmailCodeReq) (*AuthByEmailCodeResp, error)
	// ID + 密码认证
	AuthByIDPassword(context.Context, *AuthByIDPasswordReq) (*AuthByIDPasswordResp, error)
	// 批量获取指定用户ID 的基本信息
	MGetUserInfo(context.Context, *MGetUserInfoReq) (*MGetUserInfoResp, error)
	// 修改指定用户ID 的基本信息
	UpdateUserInfo(context.Context, *UpdateUserInfoReq) (*UpdateUserInfoResp, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) SendEmailCode(ctx context.Context, req *SendEmailCodeReq) (*SendEmailCodeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendEmailCode not implemented")
}
func (*UnimplementedUserServiceServer) AuthByEmailCode(ctx context.Context, req *AuthByEmailCodeReq) (*AuthByEmailCodeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthByEmailCode not implemented")
}
func (*UnimplementedUserServiceServer) AuthByIDPassword(ctx context.Context, req *AuthByIDPasswordReq) (*AuthByIDPasswordResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthByIDPassword not implemented")
}
func (*UnimplementedUserServiceServer) MGetUserInfo(ctx context.Context, req *MGetUserInfoReq) (*MGetUserInfoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MGetUserInfo not implemented")
}
func (*UnimplementedUserServiceServer) UpdateUserInfo(ctx context.Context, req *UpdateUserInfoReq) (*UpdateUserInfoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUserInfo not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_SendEmailCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendEmailCodeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).SendEmailCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/SendEmailCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).SendEmailCode(ctx, req.(*SendEmailCodeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_AuthByEmailCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthByEmailCodeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).AuthByEmailCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/AuthByEmailCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).AuthByEmailCode(ctx, req.(*AuthByEmailCodeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_AuthByIDPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthByIDPasswordReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).AuthByIDPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/AuthByIDPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).AuthByIDPassword(ctx, req.(*AuthByIDPasswordReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_MGetUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MGetUserInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).MGetUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/MGetUserInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).MGetUserInfo(ctx, req.(*MGetUserInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/UpdateUserInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateUserInfo(ctx, req.(*UpdateUserInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendEmailCode",
			Handler:    _UserService_SendEmailCode_Handler,
		},
		{
			MethodName: "AuthByEmailCode",
			Handler:    _UserService_AuthByEmailCode_Handler,
		},
		{
			MethodName: "AuthByIDPassword",
			Handler:    _UserService_AuthByIDPassword_Handler,
		},
		{
			MethodName: "MGetUserInfo",
			Handler:    _UserService_MGetUserInfo_Handler,
		},
		{
			MethodName: "UpdateUserInfo",
			Handler:    _UserService_UpdateUserInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
