// Code generated by goctl. DO NOT EDIT!
// Source: blog.proto

//go:generate mockgen -destination ./blogservice_mock.go -package blogservice -source $GOFILE

package blogservice

import (
	"context"


	"github.com/tal-tech/go-zero/zrpc"

	"github.com/he2121/go-blog/service/blog/rpc/blog"
)

type (
	GetBlogListReq     = blog.GetBlogListReq
	CreateCommentResp  = blog.CreateCommentResp
	Blog               = blog.Blog
	CommentExtra       = blog.CommentExtra
	GetCommentListResp = blog.GetCommentListResp
	UpdateCommentResp  = blog.UpdateCommentResp
	UpdateCommentReq   = blog.UpdateCommentReq
	CreateCommentReq   = blog.CreateCommentReq
	CreateBlogReq      = blog.CreateBlogReq
	UpdateBlogReq      = blog.UpdateBlogReq
	UpdateBlogResp     = blog.UpdateBlogResp
	GetCommentListReq  = blog.GetCommentListReq
	BlogExtra          = blog.BlogExtra
	GetBlogListResp    = blog.GetBlogListResp
	CreateBlogResp     = blog.CreateBlogResp
	Comment            = blog.Comment

	BlogService interface {
		//  blog 增删改查接口
		GetBlogList(ctx context.Context, in *GetBlogListReq) (*GetBlogListResp, error)
		CreateBlog(ctx context.Context, in *CreateBlogReq) (*CreateBlogResp, error)
		UpdateBlog(ctx context.Context, in *UpdateBlogReq) (*UpdateBlogResp, error)
		//  comment 增删改查接口
		GetCommentList(ctx context.Context, in *GetCommentListReq) (*GetCommentListResp, error)
		UpdateComment(ctx context.Context, in *UpdateCommentReq) (*UpdateCommentResp, error)
		CreateComment(ctx context.Context, in *CreateCommentReq) (*CreateCommentResp, error)
	}

	defaultBlogService struct {
		cli zrpc.Client
	}
)

func NewBlogService(cli zrpc.Client) BlogService {
	return &defaultBlogService{
		cli: cli,
	}
}

//  blog 增删改查接口
func (m *defaultBlogService) GetBlogList(ctx context.Context, in *GetBlogListReq) (*GetBlogListResp, error) {
	client := blog.NewBlogServiceClient(m.cli.Conn())
	return client.GetBlogList(ctx, in)
}

func (m *defaultBlogService) CreateBlog(ctx context.Context, in *CreateBlogReq) (*CreateBlogResp, error) {
	client := blog.NewBlogServiceClient(m.cli.Conn())
	return client.CreateBlog(ctx, in)
}

func (m *defaultBlogService) UpdateBlog(ctx context.Context, in *UpdateBlogReq) (*UpdateBlogResp, error) {
	client := blog.NewBlogServiceClient(m.cli.Conn())
	return client.UpdateBlog(ctx, in)
}

//  comment 增删改查接口
func (m *defaultBlogService) GetCommentList(ctx context.Context, in *GetCommentListReq) (*GetCommentListResp, error) {
	client := blog.NewBlogServiceClient(m.cli.Conn())
	return client.GetCommentList(ctx, in)
}

func (m *defaultBlogService) UpdateComment(ctx context.Context, in *UpdateCommentReq) (*UpdateCommentResp, error) {
	client := blog.NewBlogServiceClient(m.cli.Conn())
	return client.UpdateComment(ctx, in)
}

func (m *defaultBlogService) CreateComment(ctx context.Context, in *CreateCommentReq) (*CreateCommentResp, error) {
	client := blog.NewBlogServiceClient(m.cli.Conn())
	return client.CreateComment(ctx, in)
}
