// Code generated by goctl. DO NOT EDIT!
// Source: tag.proto

package server

import (
	"context"

	"github.com/he2121/go-blog/service/tag/rpc/internal/logic"
	"github.com/he2121/go-blog/service/tag/rpc/internal/svc"
	"github.com/he2121/go-blog/service/tag/rpc/tag"
)

type TagServiceServer struct {
	svcCtx *svc.ServiceContext
}

func NewTagServiceServer(svcCtx *svc.ServiceContext) *TagServiceServer {
	return &TagServiceServer{
		svcCtx: svcCtx,
	}
}

//  自定义TAG 增删改查接口
func (s *TagServiceServer) GetTagList(ctx context.Context, in *tag.GetTagListReq) (*tag.GetTagListResp, error) {
	l := logic.NewGetTagListLogic(ctx, s.svcCtx)
	return l.GetTagList(in)
}

func (s *TagServiceServer) CreateTag(ctx context.Context, in *tag.CreateTagReq) (*tag.CreateTagResp, error) {
	l := logic.NewCreateTagLogic(ctx, s.svcCtx)
	return l.CreateTag(in)
}

func (s *TagServiceServer) UpdateTag(ctx context.Context, in *tag.UpdateTagReq) (*tag.UpdateTagResp, error) {
	l := logic.NewUpdateTagLogic(ctx, s.svcCtx)
	return l.UpdateTag(in)
}

//  基本 tag 的修改与查询
func (s *TagServiceServer) UpdateBasicTag(ctx context.Context, in *tag.UpdateBasicTagReq) (*tag.UpdateBasicTagResp, error) {
	l := logic.NewUpdateBasicTagLogic(ctx, s.svcCtx)
	return l.UpdateBasicTag(in)
}

func (s *TagServiceServer) MGetBasicTag(ctx context.Context, in *tag.MGetBasicTagReq) (*tag.MGetBasicTagResp, error) {
	l := logic.NewMGetBasicTagLogic(ctx, s.svcCtx)
	return l.MGetBasicTag(in)
}
